import { StyleSheet } from "react-native";

export const RegStyles = StyleSheet.create({
  image: {
    flex: 1,
    resizeMode: "cover",
    justifyContent: "flex-end",
  },
  content_container: {
    position: "relative",
    justifyContent: "center",
    alignItems: "stretch",
    paddingHorizontal: 16,
    paddingTop: 92,
    backgroundColor: "#fff",
    borderTopLeftRadius: 25,
    borderTopRightRadius: 25,
  },
  form_container: {
    width: "100%",
    position: "relative",
    top: 0,
    height: "100%",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 40,
  },
  hero_container: {
    position: "absolute",
    top: -60,
    left: "50%",
  },
  hero_image: {
    backgroundColor: "#f6f6f6",
    width: 120,
    height: 120,
    borderRadius: 16,
  },
  hero_button: {
    position: "absolute",
    backgroundColor: "#ffffff",
    borderRadius: 10,
    bottom: 14,
    right: -12.5,
  },

  title_text: {
    fontWeight: "500",
    fontSize: 30,
    lineHeight: 35,
    textAlign: "center",
    color: "#212121",
    marginBottom: 33,
  },
  input: {
    width: "100%",
    height: 50,
    padding: 10,
    borderWidth: 1,
    borderColor: "#e8e8e8",
    marginBottom: 16,
    backgroundColor: "#f6f6f6",
    borderRadius: 8,
  },
  button: {
    backgroundColor: "#ff6c00",
    width: "100%",
    paddingVertical: 16,
    paddingHorizontal: 32,
    borderRadius: 100,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    marginTop: 27,
    marginBottom: 16,
  },
  button_text: {
    fontWeight: "400",
    fontSize: 16,
    lineHeight: 19,
    textAlign: "center",
    color: "#FFFFFF",
  },
  link_text: {
    fontWeight: "400",
    fontSize: 16,
    lineHeight: 19,
    textAlign: "center",
    color: "#1B4371",
  },
  password_view: {
    position: "relative",
  },
  showButton: {
    position: "absolute",
    right: 16,
    top: 14,
    height: "100%",
  },
  showButton_text: { fontSize: 16, color: "#1B4371" },
});
